# Network settings
INTERFACE = "0.0.0.0"
PORT = 7332

# Node keys
PUBLIC_KEY = "9GQ46rqY238rk2neSwgidap9ww5zbAN4dyqyC7j5ZnBK"
PRIVATE_KEY = "MC4CAQAwBQYDK2VwBCIEILdhTMVYFz2GP8+uKUA+1FnZTEdN8eHFzbb8400cpEU9"

# Extra data for blocks
EXTRA_DATA_TO_BLOCK = {
    "hello": "world"
}

# Timing and limits
WAIT_IF_CANT_FIND_AEFP = 4000
POLLING_TIMEOUT_TO_FIND_AEFP_FOR_QUORUM_THREAD = 10000
TIMEOUT_TO_FIND_TEMP_INFO_ABOUT_LAST_BLOCKS_BY_PREVIOUS_POOLS = 10000
TXS_MEMPOOL_SIZE = 300_000
